services:
  mysql:

    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123